# Мультиязычная поддержка бота

LANGUAGES = {
    'ru': {
        'name': '🇷🇺 Русский',
        'welcome': '😎 Добро пожаловать!\n\nВыбери язык или используй кнопки ниже:',
        'language_selected': '✅ Выбран русский язык!',
        'help': '🤖 Команды бота:\n\n/start - Запустить бота\n/help - Показать помощь\n/menu - Показать меню\n/about - О боте\n/language - Выбрать язык\n\nИли используй кнопки для навигации!',
        'about': '🤖 О боте:\n\nЯ - Сигма бот! 😎\nВерсия: 2.4.0\n💎 100 цитат великих людей!\n🎨 100+ AI изображений!\n🎧 ASMR Shorts (<2 мин)!\n🍎 AI нарезка фруктов!\n📊 Прогресс-бар загрузки!\n🌍 Мультиязычность!\nСоздан чтобы вдохновлять тебя!',
        'menu': 'Выбери действие:',
        'sigma_mode': '😎 Сигма режим активирован!',
        'motivation': '💪 Ты можешь все! Сигма не сдается!',
        'stats': '📊 Твой сигма уровень: 100/100 🔥',
        'use_menu': '🤖 Используй кнопки меню для навигации',
        'choose_language': '🌍 Выбери язык:\n\nChoose language:',
        'button_sigma': '🎯 Сигма режим',
        'button_motivation': '💪 Мотивация',
        'button_stats': '📊 Статистика',
        'button_help': '❓ Помощь',
        'button_quote': '💎 Цитата дня',
        'button_ai_image': '🎨 AI Картинка',
        'button_asmr': '🎧 ASMR Видео',
        'button_ai_fruits': '🍎 AI Нарезка',
        'button_language': '🌍 Язык',
        'button_download': '📥 Скачать видео',
        'send_link': '📥 Отправь мне ссылку на видео, и я скачаю его!',
        'downloading': '📥 Скачиваю видео',
        'processing': '⚙️ Обработка видео',
    },
    'en': {
        'name': '🇬🇧 English',
        'welcome': '😎 Welcome!\n\nChoose language or use buttons below:',
        'language_selected': '✅ English language selected!',
        'help': '🤖 Bot commands:\n\n/start - Start bot\n/help - Show help\n/menu - Show menu\n/about - About bot\n/language - Choose language\n\nOr use buttons for navigation!',
        'about': '🤖 About bot:\n\nI am Sigma bot! 😎\nVersion: 2.4.0\n💎 100 quotes from great people!\n🎨 100+ AI images!\n🎧 ASMR Shorts (<2 min)!\n🍎 AI fruit cutting!\n📊 Progress bar!\n🌍 Multilingual!\nCreated to inspire you!',
        'menu': 'Choose action:',
        'sigma_mode': '😎 Sigma mode activated!',
        'motivation': '💪 You can do everything! Sigma never gives up!',
        'stats': '📊 Your sigma level: 100/100 🔥',
        'use_menu': '🤖 Use menu buttons for navigation',
        'choose_language': '🌍 Choose language:\n\nВыбери язык:',
        'button_sigma': '🎯 Sigma Mode',
        'button_motivation': '💪 Motivation',
        'button_stats': '📊 Statistics',
        'button_help': '❓ Help',
        'button_quote': '💎 Quote',
        'button_ai_image': '🎨 AI Image',
        'button_asmr': '🎧 ASMR Video',
        'button_ai_fruits': '🍎 AI Cutting',
        'button_language': '🌍 Language',
        'button_download': '📥 Download Video',
        'send_link': '📥 Send me a video link and I\'ll download it!',
        'downloading': '📥 Downloading video',
        'processing': '⚙️ Processing video',
    },
    'ua': {
        'name': '🇺🇦 Українська',
        'welcome': '😎 Ласкаво просимо!\n\nОбери мову або використовуй кнопки нижче:',
        'language_selected': '✅ Обрано українську мову!',
        'help': '🤖 Команди бота:\n\n/start - Запустити бота\n/help - Показати допомогу\n/menu - Показати меню\n/about - Про бота\n/language - Обрати мову\n\nАбо використовуй кнопки для навігації!',
        'about': '🤖 Про бота:\n\nЯ - Сігма бот! 😎\nВерсія: 2.5.0\n💎 100 цитат великих людей!\n🎨 100+ AI зображень!\n🎧 ASMR Shorts!\n🍎 AI нарізка фруктів!\n⏱️ Вибір тривалості!\n📊 Прогрес-бар!\n🌍 8 мов!\nСтворений щоб надихати тебе!',
        'menu': 'Обери дію:',
        'sigma_mode': '😎 Сігма режим активовано!',
        'motivation': '💪 Ти можеш все! Сігма не здається!',
        'stats': '📊 Твій сігма рівень: 100/100 🔥',
        'use_menu': '🤖 Використовуй кнопки меню для навігації',
        'choose_language': '🌍 Обери мову:\n\nChoose language:',
        'button_sigma': '🎯 Сігма режим',
        'button_motivation': '💪 Мотивація',
        'button_stats': '📊 Статистика',
        'button_help': '❓ Допомога',
        'button_quote': '💎 Цитата дня',
        'button_ai_image': '🎨 AI Зображення',
        'button_asmr': '🎧 ASMR Відео',
        'button_ai_fruits': '🍎 AI Нарізка',
        'button_language': '🌍 Мова',
        'button_download': '📥 Скачати відео',
        'send_link': '📥 Відправ мені посилання на відео, і я скачаю його!',
        'downloading': '📥 Скачую відео',
        'processing': '⚙️ Обробка відео',
    },
    'es': {
        'name': '🇪🇸 Español',
        'welcome': '😎 ¡Bienvenido!\n\nElige idioma o usa los botones:',
        'language_selected': '✅ ¡Español seleccionado!',
        'help': '🤖 Comandos del bot:\n\n/start - Iniciar bot\n/help - Mostrar ayuda\n/menu - Mostrar menú\n/about - Sobre el bot\n/language - Elegir idioma\n\n¡O usa los botones!',
        'about': '🤖 Sobre el bot:\n\n¡Soy Sigma bot! 😎\nVersión: 2.5.0\n💎 ¡100 citas!\n🎨 ¡100+ imágenes AI!\n🎧 ¡ASMR Shorts!\n🍎 ¡AI corta frutas!\n⏱️ ¡Elige duración!\n📊 ¡Barra de progreso!\n🌍 ¡8 idiomas!\n¡Creado para inspirarte!',
        'menu': 'Elige acción:',
        'sigma_mode': '😎 ¡Modo Sigma activado!',
        'motivation': '💪 ¡Puedes todo! ¡Sigma nunca se rinde!',
        'stats': '📊 Tu nivel sigma: 100/100 🔥',
        'use_menu': '🤖 Usa los botones del menú',
        'choose_language': '🌍 Elige idioma:',
        'button_sigma': '🎯 Modo Sigma',
        'button_motivation': '💪 Motivación',
        'button_stats': '📊 Estadísticas',
        'button_help': '❓ Ayuda',
        'button_quote': '💎 Cita del día',
        'button_ai_image': '🎨 Imagen AI',
        'button_asmr': '🎧 ASMR Video',
        'button_ai_fruits': '🍎 AI Corta',
        'button_language': '🌍 Idioma',
    },
    'de': {
        'name': '🇩🇪 Deutsch',
        'welcome': '😎 Willkommen!\n\nWähle Sprache oder nutze die Tasten:',
        'language_selected': '✅ Deutsch ausgewählt!',
        'help': '🤖 Bot-Befehle:\n\n/start - Bot starten\n/help - Hilfe anzeigen\n/menu - Menü anzeigen\n/about - Über Bot\n/language - Sprache wählen\n\nOder nutze die Tasten!',
        'about': '🤖 Über Bot:\n\nIch bin Sigma Bot! 😎\nVersion: 2.5.0\n💎 100 Zitate!\n🎨 100+ AI Bilder!\n🎧 ASMR Shorts!\n🍎 AI schneidet Obst!\n⏱️ Wähle Dauer!\n📊 Fortschrittsbalken!\n🌍 8 Sprachen!\nErstellt um dich zu inspirieren!',
        'menu': 'Wähle Aktion:',
        'sigma_mode': '😎 Sigma-Modus aktiviert!',
        'motivation': '💪 Du schaffst alles! Sigma gibt nie auf!',
        'stats': '📊 Dein Sigma-Level: 100/100 🔥',
        'use_menu': '🤖 Nutze die Menütasten',
        'choose_language': '🌍 Wähle Sprache:',
        'button_sigma': '🎯 Sigma-Modus',
        'button_motivation': '💪 Motivation',
        'button_stats': '📊 Statistiken',
        'button_help': '❓ Hilfe',
        'button_quote': '💎 Zitat des Tages',
        'button_ai_image': '🎨 AI Bild',
        'button_asmr': '🎧 ASMR Video',
        'button_ai_fruits': '🍎 AI Schnitt',
        'button_language': '🌍 Sprache',
    },
    'fr': {
        'name': '🇫🇷 Français',
        'welcome': '😎 Bienvenue!\n\nChoisissez la langue ou utilisez les boutons:',
        'language_selected': '✅ Français sélectionné!',
        'help': '🤖 Commandes du bot:\n\n/start - Démarrer\n/help - Aide\n/menu - Menu\n/about - À propos\n/language - Choisir langue\n\nOu utilisez les boutons!',
        'about': '🤖 À propos:\n\nJe suis Sigma bot! 😎\nVersion: 2.5.0\n💎 100 citations!\n🎨 100+ images AI!\n🎧 ASMR Shorts!\n🍎 AI coupe fruits!\n⏱️ Choisir durée!\n📊 Barre de progrès!\n🌍 8 langues!\nCréé pour vous inspirer!',
        'menu': 'Choisissez action:',
        'sigma_mode': '😎 Mode Sigma activé!',
        'motivation': '💪 Vous pouvez tout! Sigma n\'abandonne jamais!',
        'stats': '📊 Votre niveau sigma: 100/100 🔥',
        'use_menu': '🤖 Utilisez les boutons du menu',
        'choose_language': '🌍 Choisissez langue:',
        'button_sigma': '🎯 Mode Sigma',
        'button_motivation': '💪 Motivation',
        'button_stats': '📊 Statistiques',
        'button_help': '❓ Aide',
        'button_quote': '💎 Citation',
        'button_ai_image': '🎨 Image AI',
        'button_asmr': '🎧 Vidéo ASMR',
        'button_ai_fruits': '🍎 AI Coupe',
        'button_language': '🌍 Langue',
    },
    'zh': {
        'name': '🇨🇳 中文',
        'welcome': '😎 欢迎！\n\n选择语言或使用按钮：',
        'language_selected': '✅ 已选择中文！',
        'help': '🤖 机器人命令：\n\n/start - 启动\n/help - 帮助\n/menu - 菜单\n/about - 关于\n/language - 选择语言\n\n或使用按钮！',
        'about': '🤖 关于机器人：\n\n我是Sigma机器人！😎\n版本：2.5.0\n💎 100条名言！\n🎨 100+张AI图片！\n🎧 ASMR短视频！\n🍎 AI切水果！\n⏱️ 选择时长！\n📊 进度条！\n🌍 8种语言！\n创建来激励你！',
        'menu': '选择操作：',
        'sigma_mode': '😎 Sigma模式已激活！',
        'motivation': '💪 你能做到一切！Sigma永不放弃！',
        'stats': '📊 你的Sigma等级：100/100 🔥',
        'use_menu': '🤖 使用菜单按钮导航',
        'choose_language': '🌍 选择语言：',
        'button_sigma': '🎯 Sigma模式',
        'button_motivation': '💪 激励',
        'button_stats': '📊 统计',
        'button_help': '❓ 帮助',
        'button_quote': '💎 每日名言',
        'button_ai_image': '🎨 AI图片',
        'button_asmr': '🎧 ASMR视频',
        'button_ai_fruits': '🍎 AI切水果',
        'button_language': '🌍 语言',
    },
    'ja': {
        'name': '🇯🇵 日本語',
        'welcome': '😎 ようこそ！\n\n言語を選択するか、ボタンを使用してください：',
        'language_selected': '✅ 日本語が選択されました！',
        'help': '🤖 ボットコマンド：\n\n/start - 起動\n/help - ヘルプ\n/menu - メニュー\n/about - について\n/language - 言語選択\n\nまたはボタンを使用！',
        'about': '🤖 ボットについて：\n\n私はシグマボット！😎\nバージョン：2.5.0\n💎 100の名言！\n🎨 100+のAI画像！\n🎧 ASMRショート！\n🍎 AIフルーツカット！\n⏱️ 時間選択！\n📊 プログレスバー！\n🌍 8言語！\nあなたを励ますために作成！',
        'menu': 'アクションを選択：',
        'sigma_mode': '😎 シグマモード起動！',
        'motivation': '💪 あなたはできる！シグマは諦めない！',
        'stats': '📊 あなたのシグマレベル：100/100 🔥',
        'use_menu': '🤖 メニューボタンを使用',
        'choose_language': '🌍 言語を選択：',
        'button_sigma': '🎯 シグマモード',
        'button_motivation': '💪 やる気',
        'button_stats': '📊 統計',
        'button_help': '❓ ヘルプ',
        'button_quote': '💎 今日の名言',
        'button_ai_image': '🎨 AI画像',
        'button_asmr': '🎧 ASMR動画',
        'button_ai_fruits': '🍎 AIカット',
        'button_language': '🌍 言語',
    },
    'ko': {
        'name': '🇰🇷 한국어',
        'welcome': '😎 환영합니다!\n\n언어를 선택하거나 버튼을 사용하세요:',
        'language_selected': '✅ 한국어가 선택되었습니다!',
        'help': '🤖 봇 명령어:\n\n/start - 시작\n/help - 도움말\n/menu - 메뉴\n/about - 정보\n/language - 언어 선택\n\n또는 버튼 사용!',
        'about': '🤖 봇 정보:\n\n저는 시그마 봇입니다! 😎\n버전: 2.5.0\n💎 100개 명언!\n🎨 100+ AI 이미지!\n🎧 ASMR 쇼츠!\n🍎 AI 과일 자르기!\n⏱️ 시간 선택!\n📊 진행률 표시!\n🌍 8개 언어!\n당신을 격려하기 위해 만들어졌습니다!',
        'menu': '작업 선택:',
        'sigma_mode': '😎 시그마 모드 활성화!',
        'motivation': '💪 당신은 할 수 있습니다! 시그마는 포기하지 않습니다!',
        'stats': '📊 당신의 시그마 레벨: 100/100 🔥',
        'use_menu': '🤖 메뉴 버튼을 사용하세요',
        'choose_language': '🌍 언어 선택:',
        'button_sigma': '🎯 시그마 모드',
        'button_motivation': '💪 동기부여',
        'button_stats': '📊 통계',
        'button_help': '❓ 도움말',
        'button_quote': '💎 오늘의 명언',
        'button_ai_image': '🎨 AI 이미지',
        'button_asmr': '🎧 ASMR 비디오',
        'button_ai_fruits': '🍎 AI 자르기',
        'button_language': '🌍 언어',
    },
    'it': {
        'name': '🇮🇹 Italiano',
        'welcome': '😎 Benvenuto!\n\nScegli lingua o usa i pulsanti:',
        'language_selected': '✅ Italiano selezionato!',
        'help': '🤖 Comandi bot:\n\n/start - Avvia\n/help - Aiuto\n/menu - Menu\n/about - Info\n/language - Scegli lingua\n\nO usa i pulsanti!',
        'about': '🤖 Info bot:\n\nSono Sigma bot! 😎\nVersione: 2.5.0\n💎 100 citazioni!\n🎨 100+ immagini AI!\n🎧 ASMR Shorts!\n🍎 AI taglia frutta!\n⏱️ Scegli durata!\n📊 Barra progresso!\n🌍 8 lingue!\nCreato per inspirarti!',
        'menu': 'Scegli azione:',
        'sigma_mode': '😎 Modalità Sigma attivata!',
        'motivation': '💪 Puoi fare tutto! Sigma non si arrende mai!',
        'stats': '📊 Il tuo livello sigma: 100/100 🔥',
        'use_menu': '🤖 Usa i pulsanti del menu',
        'choose_language': '🌍 Scegli lingua:',
        'button_sigma': '🎯 Modalità Sigma',
        'button_motivation': '💪 Motivazione',
        'button_stats': '📊 Statistiche',
        'button_help': '❓ Aiuto',
        'button_quote': '💎 Citazione',
        'button_ai_image': '🎨 Immagine AI',
        'button_asmr': '🎧 Video ASMR',
        'button_ai_fruits': '🍎 AI Taglia',
        'button_language': '🌍 Lingua',
    },
    'pt': {
        'name': '🇧🇷 Português',
        'welcome': '😎 Bem-vindo!\n\nEscolha idioma ou use os botões:',
        'language_selected': '✅ Português selecionado!',
        'help': '🤖 Comandos do bot:\n\n/start - Iniciar\n/help - Ajuda\n/menu - Menu\n/about - Sobre\n/language - Escolher idioma\n\nOu use os botões!',
        'about': '🤖 Sobre o bot:\n\nEu sou Sigma bot! 😎\nVersão: 2.5.0\n💎 100 citações!\n🎨 100+ imagens AI!\n🎧 ASMR Shorts!\n🍎 AI corta frutas!\n⏱️ Escolha duração!\n📊 Barra progresso!\n🌍 8 idiomas!\nCriado para inspirar você!',
        'menu': 'Escolha ação:',
        'sigma_mode': '😎 Modo Sigma ativado!',
        'motivation': '💪 Você pode tudo! Sigma nunca desiste!',
        'stats': '📊 Seu nível sigma: 100/100 🔥',
        'use_menu': '🤖 Use os botões do menu',
        'choose_language': '🌍 Escolha idioma:',
        'button_sigma': '🎯 Modo Sigma',
        'button_motivation': '💪 Motivação',
        'button_stats': '📊 Estatísticas',
        'button_help': '❓ Ajuda',
        'button_quote': '💎 Citação',
        'button_ai_image': '🎨 Imagem AI',
        'button_asmr': '🎧 Vídeo ASMR',
        'button_ai_fruits': '🍎 AI Corta',
        'button_language': '🌍 Idioma',
    },
    'tr': {
        'name': '🇹🇷 Türkçe',
        'welcome': '😎 Hoş geldiniz!\n\nDil seçin veya düğmeleri kullanın:',
        'language_selected': '✅ Türkçe seçildi!',
        'help': '🤖 Bot komutları:\n\n/start - Başlat\n/help - Yardım\n/menu - Menü\n/about - Hakkında\n/language - Dil seç\n\nVeya düğmeleri kullanın!',
        'about': '🤖 Hakkında:\n\nBen Sigma bot! 😎\nSürüm: 2.5.0\n💎 100 alıntı!\n🎨 100+ AI görsel!\n🎧 ASMR Shorts!\n🍎 AI meyve kesiyor!\n⏱️ Süre seç!\n📊 İlerleme çubuğu!\n🌍 8 dil!\nSizi ilham vermek için yaratıldı!',
        'menu': 'Eylem seçin:',
        'sigma_mode': '😎 Sigma modu etkin!',
        'motivation': '💪 Her şeyi yapabilirsin! Sigma asla vazgeçmez!',
        'stats': '📊 Sigma seviyeniz: 100/100 🔥',
        'use_menu': '🤖 Menü düğmelerini kullanın',
        'choose_language': '🌍 Dil seçin:',
        'button_sigma': '🎯 Sigma Modu',
        'button_motivation': '💪 Motivasyon',
        'button_stats': '📊 İstatistikler',
        'button_help': '❓ Yardım',
        'button_quote': '💎 Alıntı',
        'button_ai_image': '🎨 AI Görsel',
        'button_asmr': '🎧 ASMR Video',
        'button_ai_fruits': '🍎 AI Kesim',
        'button_language': '🌍 Dil',
    }
}

# Язык по умолчанию
DEFAULT_LANGUAGE = 'ru'

def get_text(lang_code, key):
    """Получение текста на нужном языке"""
    lang = LANGUAGES.get(lang_code, LANGUAGES[DEFAULT_LANGUAGE])
    return lang.get(key, LANGUAGES[DEFAULT_LANGUAGE].get(key, key))

